// Guards around md → DB reindex under the FILE WINS doctrine: the .md file is
// the SOURCE, the DB is a derived READ-ONLY search index. Reindex parses .md
// (CRLF-safe, fence-aware) into sections/entries; nothing renders back to .md.

import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { importChangelog, listEntries, parseChangelog } from "../../dist/docs/changelog.js";
import { importDoc, listToc, showSection } from "../../dist/docs/plan.js";
import { tempDir } from "./helpers.mjs";

test("CRLF: a Windows-written doc still splits into sections (parser was blind to \\r)", (t) => {
  const root = tempDir(t, "zemory-crlf-doc-");
  const planDir = join(root, "docs", "plan");
  const rel = join("docs", "plan", "01_spec.md");
  const abs = join(planDir, "01_spec.md");
  const dbPath = join(root, "memory.db");
  mkdirSync(planDir, { recursive: true });
  // Exactly what a Windows editor / PowerShell writes.
  writeFileSync(abs, "# Spec\r\n\r\nintro\r\n\r\n## Part A\r\n\r\nbody A\r\n\r\n## Part B\r\n\r\nbody B\r\n");

  importDoc(abs, rel, root, "plan", dbPath);

  // Before the fix: 1 blob section, heading=null (every heading was invisible).
  assert.deepEqual(
    listToc(rel, root, dbPath).map((s) => s.heading),
    ["Spec", "Part A", "Part B"],
  );
  assert.match(showSection(listToc(rel, root, dbPath)[1].id, dbPath).body, /body A/);
});

test("changelog: `## ` sub-headings INSIDE an entry body are body — not phantom entries", (t) => {
  const root = tempDir(t, "zemory-chlog-subhead-");
  const md = join(root, "05_CHANGES.md");
  const dbPath = join(root, "memory.db");
  // A real session-summary entry: the body legitimately uses `## ` sections.
  writeFileSync(
    md,
    "# Change Log\n\n## [2026-07-16] — Session summary\n\nintro\n\n## Đã làm\n\nstuff\n\n## Bàn giao\n\nnext\n\n## [2026-07-15] — Older\n\nbody\n",
  );

  assert.equal(importChangelog(md, root, dbPath), 2, "exactly 2 dated entries — sub-headings are body");
  const rows = listEntries(root, dbPath);
  assert.deepEqual(rows.map((e) => e.title), ["Session summary", "Older"]);
  assert.equal(rows.filter((e) => e.date === null).length, 0, "no dateless phantom entries");
  const parsed = parseChangelog(readFileSync(md, "utf8"));
  assert.equal(parsed.length, 2);
  assert.match(parsed[0].body, /## Đã làm/);
  assert.match(parsed[0].body, /## Bàn giao/);

  // Legacy fallback: a changelog with NO dated head still seeds entry-per-H2.
  const md2 = join(root, "legacy.md");
  writeFileSync(md2, "# Change Log\n\n## First thing\n\na\n\n## Second thing\n\nb\n");
  const root2 = join(root, "p2");
  assert.equal(importChangelog(md2, root2, dbPath), 2, "undated legacy changelog still imports");
});

test("CRLF: a Windows-written changelog merges (import used to silently report 'merged 0')", (t) => {
  const root = tempDir(t, "zemory-crlf-chlog-");
  const agentDir = join(root, "docs", "agent");
  const md = join(agentDir, "05_CHANGES.md");
  const dbPath = join(root, "memory.db");
  mkdirSync(agentDir, { recursive: true });
  writeFileSync(
    md,
    "<!-- GENERATED by zemory -->\r\n# Change Log\r\n\r\n## [2026-07-16] — CRLF entry one\r\n\r\nbody one\r\n\r\n## [2026-07-15] — CRLF entry two\r\n\r\nbody two\r\n",
  );

  assert.equal(importChangelog(md, root, dbPath), 2, "both CRLF entries must parse + merge");
  assert.deepEqual(
    listEntries(root, dbPath).map((e) => e.title),
    ["CRLF entry one", "CRLF entry two"],
  );
  // Titles must not carry a stray \r into the DB (would break dedup on re-import).
  assert.equal(importChangelog(md, root, dbPath), 0, "re-import of the same CRLF file adds nothing");
});

test("changelog import MERGES by date+title (re-import is a no-op); --replace wipes and reseeds", (t) => {
  const root = tempDir(t, "zemory-chlog-merge-");
  const dbPath = join(root, "memory.db");
  const md = join(root, "05_CHANGES.md");
  writeFileSync(
    md,
    "# Change Log\n\n## [2026-07-02] — keep me\n\nactive body\n\n## [2026-06-01] — old decision\n\nsuperseded body\n",
  );

  // First import seeds both entries; re-import of the unchanged file adds nothing.
  assert.equal(importChangelog(md, root, dbPath), 2);
  assert.equal(listEntries(root, dbPath).length, 2);
  assert.equal(importChangelog(md, root, dbPath), 0, "dedup on date+title");

  // A genuinely new hand-written entry in the .md gets merged in.
  writeFileSync(md, readFileSync(md, "utf8") + "\n## [2026-07-09] — hand-added note\n\nwritten by hand\n");
  assert.equal(importChangelog(md, root, dbPath), 1);
  assert.equal(listEntries(root, dbPath).length, 3);

  // --replace wipes this project's rows and reseeds exactly what the .md holds.
  assert.equal(importChangelog(md, root, dbPath, { replace: true }), 3);
  assert.equal(listEntries(root, dbPath).length, 3);
});
