#!/usr/bin/env node
// PreToolUse guard - layer 1 (irreversible actions) - BLOCKS BEFORE anything touches disk or network.
// Generated by `zemory hook guard` (ADAPT v2 4b). The rules live in policy.json, which GUARDS THIS FILE -
// change a rule by changing the policy (or the marker, then regenerate), NOT this file.
// Claude Code hook protocol: stdin = JSON {tool_name, tool_input}; exit 0 = let through;
// exit 2 = BLOCK, and stderr is handed back to the agent to read.
"use strict";
const fs = require("node:fs");
const crypto = require("node:crypto");
const path = require("node:path");

const HERE = __dirname;
const POLICY = JSON.parse(fs.readFileSync(path.join(HERE, "policy.json"), "utf8"));
// the hooks dir sits at <root>/<flags_dir> => root = walk back from HERE by the depth of flags_dir.
const ROOT = path.resolve(HERE, ...POLICY.flags_dir.split("/").map(() => ".."));

function deny(msg) { process.stderr.write(String(msg).trim() + "\n"); process.exit(2); }

// Window that lets ONE job be retried after its flag has been consumed (ms).
//
// Why it is needed: a PreToolUse hook only says LET THROUGH - it cannot know whether the command really ran.
// Measured 2026-08-20 while pushing 2.0.0: the guard let it through (eating the flag), then another host
// layer blocked the command => the command did NOT run and the flag was GONE, so the user had to
// create it again. The wrong direction here is 'ask again' rather than 'slip through' - safe, but real
// luc user vua dong y xong.
//
// 90 seconds: enough for one immediate retry, far shorter than the gap between two
// real decisions by the user. Once the window closes the flag is dead for good.
const FLAG_RETRY_MS = 90 * 1000;

function consumeFlag(name, subject) {
  // A flag name MISSING from the policy means an OLD policy paired with a NEW guard (the cowork set is
  // carried by hand to other machines, so the two files are bound to be out of step at times). A missing
  // name counts as NO flag - it still BLOCKS, there is simply no way around. Blocking wrongly beats a silent hole.
  const file = (POLICY.flags || {})[name];
  if (!file) return false;
  const p = path.join(ROOT, POLICY.flags_dir, file);
  if (!fs.existsSync(p)) return false;

  // Fingerprint of the JOB being asked for: a flag opens only for THAT job, it does not open the door for
  // 90 seconds for anything at all. Change the command (push another branch, delete another folder) => a different fingerprint => revoked.
  const mark = crypto.createHash("sha1").update(String(subject || name)).digest("hex").slice(0, 16);
  let prev = "";
  try { prev = fs.readFileSync(p, "utf8"); } catch {}
  const m = /ZEMORY-USED ([0-9a-f]+) ([0-9]+)/.exec(prev);
  if (m) {
    if (m[1] === mark && Date.now() - Number(m[2]) < FLAG_RETRY_MS) return true; // retry of the same job
    try { fs.unlinkSync(p); } catch {} // a different job or past the window => revoked, ask again
    return false;
  }
  // First time: do NOT delete at once, only stamp it used. The flag dies when the window closes or when
  // someone asks for a different job - so it is still 'one flag for one job', it merely forgives one retry.
  try {
    fs.writeFileSync(p, "ZEMORY-USED " + mark + " " + Date.now() + "\n");
  } catch {
    try { fs.unlinkSync(p); } catch {} // cannot write => old behaviour: one use and done
  }
  return true;
}

// The sentence that points the way around. An OLD policy declaring no flag name used to print
// `docs/hooks/undefined`, telling people to create a file literally named "undefined" - a silent
// instruction bug that only surfaces when someone follows it. Now it says the policy is missing the name, and how to regenerate.
function flagTip(name) {
  const file = (POLICY.flags || {})[name];
  if (!file) return "\n(This policy build does not declare the flag `" + name + "` => there is NO way around. Run `zemory hook guard` to regenerate the policy.)";
  return "\nHas the user agreed? -> create the flag `" + POLICY.flags_dir + "/" + file + "` and try again (one use).";
}

function relToRoot(p) {
  const s = String(p).replace(/\\/g, "/");
  const root = ROOT.replace(/\\/g, "/");
  const rel = path.relative(root, s).replace(/\\/g, "/");
  if (rel && !rel.startsWith("..")) return rel;
  const base = root.replace(/\/+$/, "").split("/").pop();
  const marker = "/" + base + "/";
  if (s.includes(marker)) return s.split(marker).slice(1).join(marker);
  return s.replace(/^\/+/, "");
}

function globToRe(pat) {
  return new RegExp("^" + pat.replace(/[.+^$(){}|[\]\\]/g, "\\$&").replace(/\*/g, ".*").replace(/\?/g, ".") + "$", "i");
}
function nameMatches(rel, patterns) {
  const name = rel.split("/").pop() || "";
  return patterns.some((p) => globToRe(p).test(name));
}

// MOT hàm khop duy nhat cho CA HAI nhanh (ghi + xoa).
// Match a PREFIX (a fixed path) OR a GLOB (with `*`) - a glob can express what a prefix
// cannot: `data/*/01_raw` (the raw input of EVERY case, whose names are not known in advance).
// Without globs you would either list every case by hand (nobody can maintain that) or block all of `data`
// (which blocks 02_processing where the agent writes constantly => the gate gets ignored).
//
// WHY IT MUST BE SHARED: before 2026-08-24 the WRITE branch had globs while the DELETE branch had only prefixes, so
// declaring `data/*/01_raw` blocked writes but NOT deletes - exactly the silent-hole class. Two copies
// of the same matcher are certain to drift apart; now there is only one source.
function underProtected(rel, prefix) {
  const pre = String(prefix).replace(/\/+$/, "");
  if (pre.includes("*")) return globToRe(pre).test(rel) || globToRe(pre + "/*").test(rel);
  return rel === pre || rel.startsWith(pre + "/");
}

function checkWrite(rel) {
  if (nameMatches(rel, POLICY.secret_allow || [])) return;
  for (const prefix of POLICY.protected_write || []) {
    const hit = underProtected(rel, prefix);
    if (hit) {
      if (consumeFlag("docs_write", rel)) return;
      deny("BLOCKED (guard layer 1): writing into `" + prefix + "` - " + POLICY.protected_write_reason +
        "\nDid the user approve it this session? -> create the flag `" + POLICY.flags_dir + "/" + POLICY.flags.docs_write + "` and try again (the flag is good for ONE use).");
    }
  }
}

function checkRead(rel) {
  if (nameMatches(rel, POLICY.key_read_block || [])) {
    deny("BLOCKED (guard layer 1): reading the key file `" + rel + "` - " + POLICY.key_read_reason);
  }
}

// Drop ONLY the payload of -m/--message and heredocs (where false positives are born), keeping the rest intact.
// Dropping EVERY quoted string was a measured hole: a command wrapped in bash -c "..." was wiped clean =>
// the guard saw nothing => every layer-1 rule went silent.
function stripMessages(cmd) {
  let out = cmd.replace(/(?:-m|--message=?)\s*(['"])[\s\S]*?\1/g, " -m MSG ");
  out = out.replace(/<<-?\s*(['"]?)(\w+)\1[\s\S]*?^\2/gm, " HEREDOC ");
  return out;
}

// Read `git` as A COMMAND, not as a fragment of a path (fixed 2026-08-20, prompted by
// the PBI repo report plus a reproduction: `cat .git/hooks/pre-push` was read as "git push" => BLOCKED WRONGLY
// right when someone follows the `hook guard` instructions):
//   (?<!\.)  — `git` after a dot is a path or a name (`.git/hooks` · `repo.git`), not the command
//   (?![\\/]) — `git` glued to `/` or `\` is a path carrying on (`.git/hooks/...`)
// Van bat du 8 ca do 2026-08-20: `git push` · `cd x && git push` · `/usr/bin/git push` ·
// `sudo git push` · `env A=1 git push`. Do NOT use "first token of the line" — the last three cases would slip.
const GIT_CMD = "(?<!\\.)\\bgit\\b(?![\\\\/])";
// `push` must be ONE ARGUMENT, not a fragment of a longer name (and, measured 2026-08-22 by this very
// session): `\\bpush\\b` also matches a token INSIDE a file name because `-` and `.` are non-word characters, so
// `git check-ignore -v docs/hooks/.allow-push` was blocked as a real push command — that is, the very
// even the command that INSPECTS THE FLAG could not run. Added (?<![\w.-]) so it catches only `push` in its real sense.
const PUSH_ARG = "(?<![\\w.-])push\\b";

// ── COMMAND POSITION: match a TOKEN where a command belongs, not a string anywhere ─────
//
// Hole measured 2026-08-26 (hit three times in ONE real working session): the guard only scanned STRINGS, so a
// command name sitting inside a piece of PROSE was blocked too:
//     echo "=== git remote (not pushed) ==="   -> blocked by the git push rule
//     echo "trying rm -rf"                     -> blocked by the recursive delete rule
// Blocking wrongly leads straight to "a noisy gate is an ignored gate" (rule 7, .claude/skills/audit).
//
// The fix: split the line into SEGMENTS (outside quotes), read each segment's FIRST WORD as its
// command name, then scan only the segments where that name really IS the command. `echo` is never `git`.
//
// 🔴 MANDATORY EXCEPTION - INTERPRETERS: `bash -c "…"` · `node -e "…"` · `python -c "…"` carry
// the quoted content IS the real command. On meeting an interpreter (in ANY segment, including the last one in
// a pipe such as `echo x | bash`) we go back to scanning the WHOLE line as before - blocking wrongly beats a hole.
const SEG_WRAPPER = /^(sudo|doas|env|command|nohup|time|nice|exec)$/i;
const SEG_INTERP = /^(bash|sh|zsh|dash|ksh|pwsh|powershell|cmd|node|nodejs|python|python3|py|perl|ruby|deno|bun)$/i;

// Split on ; | & and newlines, BUT ignore a separator that sits inside quotes.
function splitSegments(cmd) {
  const out = [];
  let cur = "";
  let q = null;
  for (let i = 0; i < cmd.length; i++) {
    const c = cmd[i];
    if (q) {
      cur += c;
      if (c === q && cmd[i - 1] !== "\\") q = null;
      continue;
    }
    if (c === '"' || c === "'") { q = c; cur += c; continue; }
    if (c === ";" || c === "\n" || c === "&" || c === "|") { out.push(cur); cur = ""; continue; }
    cur += c;
  }
  out.push(cur);
  return out.filter((s) => s.trim());
}

// The command name of a segment: drop environment assignments (A=1), drop wrappers (sudo/env/…), take
// basename va bo nhay. `/usr/bin/git` -> `git`; `env A=1 sudo git` -> `git`.
function cmdWordOf(seg) {
  for (const raw of seg.trim().split(/\s+/)) {
    const tok = raw.replace(/^["']|["']$/g, "");
    if (!tok) continue;
    if (/^[A-Za-z_][\w]*=/.test(tok)) continue;
    const name = tok.replace(/\\/g, "/").split("/").pop() || "";
    if (SEG_WRAPPER.test(name)) continue;
    return name.toLowerCase();
  }
  return "";
}

// The region a rule MUST SCAN. An interpreter means the whole line. Otherwise only the segments with that name.
function zonesFor(cmd, nameRe) {
  const segs = splitSegments(cmd);
  if (segs.some((s) => SEG_INTERP.test(cmdWordOf(s)))) return [cmd];
  return segs.filter((s) => nameRe.test(cmdWordOf(s)));
}
const hitsIn = (cmd, nameRe, re) => zonesFor(cmd, nameRe).some((z) => re.test(z));

// Does any segment put that command name in COMMAND POSITION. Used by rules whose pattern SPANS a pipe
// (`Get-ChildItem -Recurse | Remove-Item`): cutting the segment at `|` leaves neither half matching —
// a regression measured on the day of the 2026-08-26 fix. So: command position decides WHETHER to
// scan, and once it scans, it scans THE WHOLE LINE.
const anyCmdIs = (cmd, nameRe) => splitSegments(cmd).some((s) => nameRe.test(cmdWordOf(s)));

function checkBash(cmd) {
  const bare = stripMessages(cmd);

  if (hitsIn(bare, /^git$/, new RegExp(GIT_CMD + "[^\\n;|&]*" + PUSH_ARG))) {
    if (!consumeFlag("push", bare)) {
      deny("BLOCKED (guard layer 1): `git push` - push only when the user says so (02_RULES Git)." +
        "\nDid the user just say so? -> create the flag `" + POLICY.flags_dir + "/" + POLICY.flags.push + "` and run again (one use).");
    }
  }

  if (hitsIn(bare, /^git$/, new RegExp(GIT_CMD + "[^\\n;|&]*\\bcommit\\b[^\\n;|&]*(--no-verify|\\s-n\\b)"))) {
    deny("BLOCKED (guard layer 1): `git commit --no-verify` bypasses pre-commit - there is no way around.");
  }

  if (hitsIn(bare, /^git$/, new RegExp(GIT_CMD + "[^\\n;|&]*\\badd\\b[^\\n;|&]*(\\s-A\\b|\\s--all\\b|\\s\\.\\s*($|;|&|\\|))"))) {
    if (!consumeFlag("git_add_all", bare)) {
      deny("BLOCKED (guard layer 1): `git add -A/.` - this very command put a secret on GitHub (2026-08-04)." +
        "\nList the files explicitly; if you truly need the whole tree, ask the user to create the flag `" +
        POLICY.flags_dir + "/" + POLICY.flags.git_add_all + "` (one use).");
    }
  }

  // Secrets entering staging or a commit. Two deliberate boundaries (fixed 2026-08-20):
  //   · scan ONLY the tokens of the EXACT SEGMENT holding the git command (split on ;|&) — a secret name mentioned
  //     inside `echo "example.env staged"` on the same command line is no longer blocked wrongly (it used to scan
  //     the whole line; people then learn to stop writing self-checking commands, and that is the real damage).
  //   · `git add "app/x.env"` is STILL caught (quotes are only separators within that segment).
  //     ⚠ This claim was once WRONG because the pattern set lacked `*.env` — now re-measured with the new set.
  const GIT_STAGE = new RegExp(GIT_CMD + "[^\\n;|&]*\\b(add|commit|mv)\\b");
  if (GIT_STAGE.test(bare)) {
    for (const seg of bare.split(/[\n;|&]+/)) {
      if (!GIT_STAGE.test(seg)) continue;
      for (const tok of seg.split(/[\s'"]+/)) {
        const name = tok.replace(/\\/g, "/").split("/").pop();
        if (!name) continue;
        if (nameMatches(name, POLICY.secret_allow || [])) continue;
        if (nameMatches(name, POLICY.secret_names || [])) {
          deny("BLOCKED (guard layer 1): `" + name + "` matches a secret pattern inside a git command - " + POLICY.secret_reason);
        }
      }
    }
  }

  // XOA - nhanh HEP CO CHU DICH (them 2026-08-10).
  //
  // Why it did not exist before: guard 1.2.0 generated 5 branches, none about deletion. A real test
  // tren ban do: `rm -rf docs/agent`, `Remove-Item -Recurse -Force data`, `del /S /Q`
  // all returned rc=0 and slipped clean through. Meanwhile 02_RULES Behaviour states plainly that deletion is
  // IRREVERSIBLE and the user must be asked first - the rule had words but no machine latch.
  //
  // Why NARROW rather than blocking every delete: an agent deletes temp files all day; blocking them all
  // means every command needs a flag, and "a noisy gate is an ignored gate" (02_RULES). So it blocks
  // only the two things that truly cannot be undone:
  //   (a) a RECURSIVE or mass delete - one command sweeping the whole tree
  //   (b) deleting exactly a declared `protected` path, or one matching a secret pattern - even without recursion
  const RECURSIVE_DEL =
    /\brm\b[^\n;|&]*\s-[a-z]*r[a-z]*\b|\bRemove-Item\b[^\n;|&]*-Recurse\b|\brmdir\b[^\n;|&]*\/[sS]\b|\bdel\b[^\n;|&]*\/[sS]\b/;
  const ANY_DEL = /\brm\b|\bRemove-Item\b|\brmdir\b|\bdel\b|\bUnlink\b/;
  // MASS DELETION THAT USES NONE OF THE KEYWORDS ABOVE (added 2026-08-11 after measuring a 28-case matrix).
  // The old branch only looked at `rm -r` and friends; in practice 8 whole-tree paths slipped clean through:
  // `find -delete` · `find -exec rm` · `git clean -fdx` · `robocopy /MIR` (mirror =
  // deletes what the source does not have) · `fs.rmSync(recursive)` inside `node -e` · `shutil.rmtree`
  // inside `python -c` · `xargs rm` · `Get-ChildItem -Recurse | Remove-Item` (a pipe, with
  // no path to match against). All are as irreversible as `rm -rf`.
  const MASS_DEL =
    /\bfind\b[^\n]*-delete\b|\bfind\b[^\n]*-exec[^\n]*\brm\b|\bgit\s+clean\b[^\n]*-[a-z]*[fdx]|\brobocopy\b[^\n]*\/(MIR|PURGE)\b|\brmSync\s*\([^)]*recursive|\brmtree\s*\(|\bxargs\b[^\n]*\brm\b|\bGet-ChildItem\b[^\n]*\|[^\n]*\bRemove-Item\b/i;
  const MASS_CMDS = /^(find|git|robocopy|xargs|get-childitem|gci|ls|dir|remove-item|ri|rm)$/;
  if ((anyCmdIs(bare, MASS_CMDS) || SEG_INTERP.test(cmdWordOf(bare))) && MASS_DEL.test(bare) && !consumeFlag("delete", bare)) {
    deny("BLOCKED (guard layer 1): MASS deletion (a whole-tree sweep) - irreversible, and 02_RULES requires asking the user first." +
      flagTip("delete"));
  }

  // DISCARDING UNCOMMITTED WORK - the rule already had WORDS in 02_RULES S Git ("no reset --hard/clean on
  // the user's uncommitted work without asking") but measured 2026-08-11 there was NO latch: both
  // `git reset --hard` and `git checkout -- .` sailed through. Losing uncommitted work is losing it
  // for good - git cannot rescue what never entered git.
  const DISCARD =
    /\bgit\s+reset\b[^\n]*--hard\b|\bgit\s+checkout\b[^\n]*--\s|\bgit\s+checkout\s+\.|\bgit\s+restore\b[^\n]*(\.|--staged)|\bgit\s+stash\s+(drop|clear)\b/;
  if (hitsIn(bare, /^git$/, DISCARD) && !consumeFlag("discard", bare)) {
    deny("BLOCKED (guard layer 1): a command DISCARDING uncommitted work - 02_RULES S Git requires asking the user first." +
      flagTip("discard"));
  }

  // EMPTYING CONTENT without "deleting" the file. By the irreversibility test it equals a
  // deletion: the file is still there but its insides are gone. Only two commands are taken, ones with no
  // purpose other than emptying - so the gate does not become noise.
  //   Deliberately LEFT THROUGH (reported, not blocked): `> file` and `echo '' > file` (output redirection
  //   is an everyday operation, blocking it is daily noise) and `mv` (renaming and tidying a repo is
  //   ordinary work). Blocking those would require telling "overwrite an EXISTING repo file" apart from "create a
  //   new file", and that is its own job - do not stuff it in here for completeness.
  if (hitsIn(bare, /^(truncate|clear-content)$/, /\btruncate\b[^\n]*-s\s*0\b|\bClear-Content\b/) && !consumeFlag("overwrite", bare)) {
    deny("WARNING (guard layer 1): a command EMPTYING a file - the old content is gone for good." +
      "\nASK THE USER first." + flagTip("overwrite"));
  }

  // Names of REAL delete commands (not `echo`/`grep` merely mentioning the letters "rm"). `unlink` has both forms.
  const DEL_CMDS = /^(rm|remove-item|ri|rmdir|rd|del|erase|unlink)$/;
  if (hitsIn(bare, DEL_CMDS, ANY_DEL)) {
    const recursive = hitsIn(bare, DEL_CMDS, RECURSIVE_DEL);
    // Ask for the ONE-USE flag for the whole command line, then remember it: `consumeFlag` has side effects (stamping
    // and revoking), so calling it per token wastes I/O and reads badly. One flag serves
    // BOTH the protected branch AND the recursive-delete branch - the user does not ask twice for one command.
    let delFlagMemo = null;
    const delFlagOk = () => (delFlagMemo === null ? (delFlagMemo = consumeFlag("delete", bare)) : delFlagMemo);
    // Scan ONLY the tokens of the EXACT SEGMENT holding the delete command (split on ;|&) — same shape and same reason
    // the same as the git branch above (fixed 2026-08-24, user approved 21/08): rm build.log && echo check-prod.env
    // was once BLOCKED WRONGLY because an .env name was mentioned in an echo. Scanning the whole line teaches people
    // to stop writing self-checking commands — that is the real damage. RECURSIVE_DEL still examines the WHOLE command.
    for (const seg of bare.split(/[\n;|&]+/)) {
      if (!ANY_DEL.test(seg)) continue;
      for (const tok of seg.split(/[\s'"]+/)) {
      if (!tok || tok.startsWith("-") || tok.startsWith("/")) continue;
      const rel = tok.replace(/\\/g, "/").replace(/^\.\//, "");
      const name = rel.split("/").pop();
      if (name && !nameMatches(name, POLICY.secret_allow || []) && nameMatches(name, POLICY.secret_names || [])) {
        deny("BLOCKED (guard layer 1): a delete command touching the secret file `" + name + "` - " + POLICY.secret_reason);
      }
      for (const prefix of POLICY.protected_write || []) {
        // The SAME function as the write branch - see `underProtected`. This spot used to compare prefixes only.
        if (underProtected(rel, prefix)) {
          // 🔴 BLOCK, THEN ASKING IS ALLOWED (user ruling 2026-09-04). This spot used to `deny()`
          // ABSOLUTELY, with no way around at all - not even `.allow-delete`. That was wrong on two counts:
          //   1 INCONSISTENT with the branch right below: `mv <protected>/x /tmp` has
          //      EXACTLY the same consequence as deleting (that branch's own comment says so) and it DOES have a way around.
          //      Two paths, one consequence, two different gates => people learn to take the `mv` road.
          //   ② Trai doctrine `02_RULES §Guardrail`: *chu la tang QUYET DINH, may la tang DO
          //      SHORT*. A gate with no path for the user to approve is the machine acting as THE DECIDER.
          // Use the `delete` flag and NOT `docs_write`: a round where the user approved WRITING to a
          // protected path must not turn into approval to DELETE. The fingerprint follows the COMMAND, so one flag covers
          // tron lenh xoa do (cung khuon vua vá cho nhanh doi ten).
          // ⚠ Do NOT `return` here: it would exit the WHOLE guard function, skipping the secret check
          // on the remaining tokens, the RECURSIVE delete check, and the `mv`/redirection branch
          // below - meaning one delete flag would open the door for everything else on the same command line.
          if (!delFlagOk()) {
            deny("BLOCKED (guard layer 1): deleting inside the declared protected path `" + prefix + "` - " +
              POLICY.protected_write_reason + flagTip("delete"));
          }
        }
      }
      }
    }
    if (recursive && !delFlagOk()) {
      deny("BLOCKED (guard layer 1): a RECURSIVE delete - an irreversible operation, and 02_RULES requires asking the user first." +
        flagTip("delete"));
    }
  }

  // ── WRITING / MOVING through a COMMAND (not only through the Write/Edit tools) ─────────
  //
  // Hole measured 2026-08-26: `checkWrite` only runs for the Write/Edit/MultiEdit tools, so writing to a
  // protected path through the SHELL went uninspected. Measured for real: it wrote into `01_CONSTITUTION` and
  // OUTSIDE the repo, though both sit inside protected.
  //     echo x >> docs/agent/05_TODO.md        (redirection)
  //     python -c "open('data/x','w').write()" (script)
  // And hole 3 gapes just as wide: `mv <protected>/x /tmp` has EXACTLY the consequence of a delete yet slipped clean through — the file leaves
  // the protected path, only the name of the operation differs.
  //
  // 🔴 LIMIT — do NOT read this as "the guard covers everything":
  // This layer only sees paths WRITTEN OUT LITERALLY in the command. A path built at runtime (string
  // concatenation, read from a variable, a file or stdin) is NOT seen, and cannot be - a hook reading
  // a command string cannot know where the script will write. Real blocking belongs at the operating-system layer
  // (file permissions / ACL), not here. This branch only closes the EASIEST road.
  const REDIRECT = /(?:^|[\s;&|])>{1,2}\s*(["']?)([^\s"'|;&]+)\1/g;
  const MOVERS = /^(mv|move|move-item|mi|rename|ren|cp|copy|copy-item|robocopy|rsync)$/;
  const WRITE_VERB = /\b(open\s*\(|write|writeFile|appendFile|writeFileSync|appendFileSync|Set-Content|Add-Content|Out-File|dump|save)\b/i;

  // 🔴 FINGERPRINT PER COMMAND, NOT PER PATH (fixed 2026-09-04, reported from the Dept_OPS repo).
  // This spot used to call `consumeFlag("docs_write", rel)` — the fingerprint was computed over ONE path.
  // But `mv A B` touches TWO paths, and if both sit inside protected then every run:
  //   1 examines the SOURCE A -> the flag is unstamped -> stamp sha1(A) -> LET THROUGH
  //   2 examines the TARGET B -> finds the stamp sha1(A) != sha1(B) -> DELETES THE FLAG -> BLOCKS
  // The next round with a fresh flag has the SOURCE consume it first, leaving the target empty-handed => AN
  // INESCAPABLE LOOP, however many flags the user grants. The `FLAG_RETRY_MS` window cannot
  // save it: it allows a retry of the SAME consumed subject, whereas here the source consumes a
  // NEW flag every round, so it never reaches that state.
  // This is a BUG, not a policy: the message below invites the user to create a flag, meaning the design
  // DELIBERATELY lets an approving user through — yet with a rename that invitation can never be
  // fulfilled. And a gate that promises a way through but cannot deliver pushes people to drop the path from
  // `protected` altogether — costing more than it gains.
  // Now: one flag covers the WHOLE COMMAND (`bare`), the same shape every other branch in this file already
  // uses (`push`/`delete`/`discard`/`git_add_all` all fingerprint the command). It is still "one use
  // for one job": change the command => a different fingerprint => revoked.
  const flagWritePath = (raw, how) => {
    const tok = String(raw).replace(/^["']|["']$/g, "");
    if (!tok || tok.startsWith("-")) return;
    const rel = relToRoot(tok.replace(/\\/g, "/").replace(/^\.\//, ""));
    for (const prefix of POLICY.protected_write || []) {
      if (!underProtected(rel, prefix)) continue;
      if (consumeFlag("docs_write", bare)) return;
      deny("BLOCKED (guard layer 1): " + how + " `" + rel + "` which sits inside the protected path `" + prefix +
        "` - " + POLICY.protected_write_reason +
        "\nDid the user approve it this session? -> create the flag `" + POLICY.flags_dir + "/" + POLICY.flags.docs_write +
        "` and try again (the flag is good for ONE use).");
    }
  };

  for (const seg of splitSegments(bare)) {
    const word = cmdWordOf(seg);
    // 1 redirection `>`/`>>` — the target is a file being overwritten or appended to, whatever command stands in front.
    let m;
    REDIRECT.lastIndex = 0;
    while ((m = REDIRECT.exec(seg))) flagWritePath(m[2], "writing (redirection) into");
    // 2 MOVE / COPY commands: a SOURCE inside protected means it leaves the protected area (hole 3);
    //    a TARGET inside protected means writing into that area.
    if (MOVERS.test(word)) {
      const args = seg.trim().split(/\s+/).slice(1).filter((t) => t && !t.startsWith("-"));
      const removes = /^(mv|move|move-item|mi|rename|ren)$/.test(word);
      args.forEach((a, i) => {
        const last = i === args.length - 1;
        if (last) flagWritePath(a, "writing (target of " + word + ") into");
        else if (removes) flagWritePath(a, "MOVING OUT OF (source of " + word + ")");
      });
    }
    // 3 interpreters: judge only when the payload holds both a protected path AND a writing verb — to
    //    avoid wrongly blocking `python -c "print(open('data/x').read())"` (reading, not writing).
    if (SEG_INTERP.test(word) && WRITE_VERB.test(seg)) {
      for (const tok of seg.split(/[\s'"(),]+/)) {
        // Do NOT require the token to contain a `/`: a protected path is often a BARE NAME at the repo root
        // (`.vault` · `attic` · `data`) — measured 2026-08-26 across 7 of 9 PBI repos, and at first they slipped clean through
        // by the "must contain /" condition. `underProtected` is the real decider; a meaningless token
        // (`w` · `1`) matches no path, so it produces no false positive.
        if (!tok || tok.startsWith("-")) continue;
        flagWritePath(tok, "writing (through " + word + ") into");
      }
    }
  }

  // Reading the contents of a key file through the shell - the same rule as checkRead.
  //
  // Scan ONLY tokens that LOOK LIKE A FILE BEING READ, not every token in the command line.
  // The old build scanned everything: if the command line CONTAINED `head`/`cat`/... then every token was compared, so
  // `grep -rln "id_rsa" src/ | head` was blocked - the key name was in the SEARCH PATTERN, not
  // a file being read. That is exactly the wrong-block measured 2026-08-11 (it blocked the very
  // audit command sent to inspect git history), and rule 7 exists to catch this class: a gate that blocks wrongly makes
  // people find a way around, and then the whole gate means nothing.
  //
  // Three signs count as "a file being read" - all of them caught real cases:
  //   1. the token holds a path separator  ->  cat /etc/ssh/id_rsa
  //   2. a token standing RIGHT AFTER a reading command (skipping -x flags)  ->  cat id_rsa | grep x
  //   3. token cuoi cau  ->  head id_rsa
  const READER = /^(cat|less|more|head|tail|type|base64|xxd|od|strings|cp|scp)$/;
  if (/\b(cat|less|more|head|tail|type|base64|xxd|od|strings|cp|scp)\b/.test(bare)) {
    const toks = cmd.split(/[\s'";|&]+/).filter(Boolean);
    let afterReader = false;
    toks.forEach((tok, i) => {
      const bareTok = tok.replace(/^["']|["']$/g, "");
      const looksLikePath = /[\/\\]/.test(bareTok);
      const isLast = i === toks.length - 1;
      const suspect = looksLikePath || afterReader || isLast;
      if (READER.test(bareTok.replace(/\\/g, "/").split("/").pop() || "")) {
        afterReader = true;
      } else if (!bareTok.startsWith("-")) {
        afterReader = false;
      }
      if (!suspect) return;
      const name = bareTok.replace(/\\/g, "/").split("/").pop();
      if (name && nameMatches(name, POLICY.key_read_block || [])) {
        deny("BLOCKED (guard layer 1): a shell command touching the contents of the key file `" + name + "` - " + POLICY.key_read_reason);
      }
    });
  }
}

function main() {
  let payload;
  try {
    // Strip the BOM before parsing: a PowerShell 5.1 pipe inserts U+FEFF at the head of stdin (measured
    // 2026-08-07 — the same family as the BOM marker bug), and without stripping it every rule goes silent (fail-open).
    payload = JSON.parse(fs.readFileSync(0, "utf8").replace(/^\uFEFF/, ""));
  } catch {
    process.exit(0); // input unreadable means no verdict - a broken guard must not block blindly
  }
  const tool = payload.tool_name || "";
  const ti = payload.tool_input || {};
  // Recognise by the SHAPE of the call, not by a fixed list of NAMES.
  // Measured 2026-08-20: the guard only knew the name `Bash`, so EVERY command-guarding branch (an unrequested git push,
  // git add -A, secrets into git, recursive deletes) could be bypassed entirely by switching to the
  // `PowerShell` tool - the MAIN terminal tool on Windows, available in the SAME session. The recognising regex
  // still worked (the Bash branch catches PowerShell syntax too); only the NAME gate judged wrongly.
  // Hence: anything carrying `command` is inspected as a shell command whatever the tool is called - and it keeps working with
  // future tools without bumping zemory.
  const isCommandTool = typeof ti.command === "string" && ti.command !== "";
  const isWriteTool = tool === "Write" || tool === "Edit" || tool === "MultiEdit" || tool === "NotebookEdit";
  if (isWriteTool) {
    const p = ti.file_path || ti.notebook_path || "";
    if (p) checkWrite(relToRoot(p));
    // OVERWRITING = losing the old content, as good as a delete. `Write` replaces the WHOLE file; `Edit`
    // does not (it edits a region), so ONLY `Write` is asked about.
    //
    // Why ASK rather than FORBID (user ruling 2026-08-11): overwriting is an ordinary everyday
    // operation, and forbidding it outright turns the gate into noise that gets ignored. But it is irreversible, so
    // there must be a warning FIRST - in the spirit of "an irreversible rule needs a machine latch".
    //
    // Applied ONLY inside the repo tree: files in a temp or scratchpad folder are overwritten constantly, and blocking there
    // creates noise while protecting nothing.
    if (tool === "Write" && p) {
      const rel = relToRoot(p);
      const inside = !rel.startsWith("..") && !path.isAbsolute(rel);
      let sizeNow = 0;
      try {
        sizeNow = fs.existsSync(p) ? fs.statSync(p).size : 0;
      } catch {
        sizeNow = 0; // cannot stat means no verdict (fail-open)
      }
      if (inside && sizeNow > 0 && !consumeFlag("overwrite", rel)) {
        deny("WARNING (guard layer 1): OVERWRITING `" + rel + "` (" + sizeNow + " bytes present) - " +
          "the old content is gone for good and cannot be undone.\nASK THE USER first." + flagTip("overwrite") +
          "\nTo change only a region use Edit - Edit is NOT asked about.");
      }
    }
  } else if (tool === "Read") {
    if (ti.file_path) checkRead(relToRoot(ti.file_path));
  } else if (isCommandTool) {
    checkBash(String(ti.command));
  }
  process.exit(0);
}
main();
