// Session digest (plan 06) — a DERIVED, per-session summary lens for cheap-token
// recall: read the digest first, drill down to real messages via anchors only
// when needed. DETERMINISTIC + EXTRACTIVE (no LLM): it only picks verbatim lines
// and metadata, so it can never hallucinate; it reads ONLY messages of one
// session, so it can never mix sessions. Rebuildable and safe to delete —
// regenerated by `brain scan` (hash-guarded) and `brain digest --all`.

import { type BrainDB, BRAIN_DB, openBrain } from "./db.js";
import { blendRecency, recencyEnabled } from "./recency.js";

export interface Anchored {
  text: string;
  /** Source message id to drill down to (progressive disclosure). */
  id: number;
}

export interface DigestMeta {
  source: string;
  host: string;
  project_root: string | null;
  messages: number;
  from: string | null;
  to: string | null;
}

export interface Digest {
  session_id: string;
  kind: string;
  tasks: Anchored[];
  paths: string[];
  decisions: Anchored[];
  errors: Anchored[];
  outcome: string;
  meta: DigestMeta;
  updated_at: string | null;
}

interface MsgRow {
  id: number;
  role: string | null;
  content: string | null;
  tool_name: string | null;
  timestamp: string | null;
}

const DECISION_RE = /\b(ch[oố]t|quy[eế]t[- ]?đ[iị]nh|th[oố]ng nh[aấ]t|decide[dr]?|use\b|drop\b|ch[oọ]n)\b|CH[OỐ]T/i;
// STRUCTURAL error signals only — a doc/read tool_result that merely mentions the
// word "error"/"lỗi" is NOT an error, so bare-word matches are deliberately excluded.
const ERROR_RE = /(traceback|exception|exit code [1-9]|\bexit [1-9]\d*\b|not recognized|command not found|no such file|permission denied|\berror:|IndentationError|SyntaxError|cannot find|✗)/i;
// Windows drive paths, or unix paths NOT preceded by a word char (so "a/b/c"
// inside prose like "registry/router/hooks" is not mistaken for a real path).
const PATH_RE = /(?:[A-Za-z]:\\[\w .%\\/-]{3,}|(?<![\w])\/(?:[\w.-]+\/){2,}[\w.-]+)/g;

// Lines that are NOT natural language (agent tool calls / tool output / host
// notices) — excluded from tasks & decisions so the digest stays human-readable.
const NON_NL = /^\s*(\[tool[_ ]result|\[tool[_ ]use|\[Request interrupted|\[No response)/i;
const TOOL_RESULT = /^\s*\[tool[_ ]result/i;

function clip(s: string, n = 180): string {
  const one = s.replace(/\s+/g, " ").trim();
  return one.length > n ? one.slice(0, n) + "…" : one;
}

// Bump when the extraction logic changes → every stored digest's signature no
// longer matches, so `brain scan` / `brain digest --all` regenerates them all.
const DIGEST_VERSION = 3;

/** Staleness signature: logic version + message count + last id + last timestamp. */
function signature(msgs: MsgRow[]): string {
  const n = msgs.length;
  const last = msgs[n - 1];
  return `v${DIGEST_VERSION}:${n}:${last ? last.id : 0}:${last ? last.timestamp ?? "" : ""}`;
}

/**
 * (Re)build the extractive digest for ONE session. Hash-guarded: if the session
 * is unchanged since the stored digest (same signature, still extractive), it is
 * a no-op. Returns whether it wrote. Never throws on empty/odd input (fail-open).
 */
export function buildDigest(db: BrainDB, sessionId: string): { built: boolean; reason?: string } {
  const s = db
    .prepare(
      "SELECT id, source, project_root, cwd, host, started_at, ended_at, message_count FROM sessions WHERE id = ?",
    )
    .get(sessionId) as
    | {
        id: string;
        source: string;
        project_root: string | null;
        cwd: string | null;
        host: string | null;
        started_at: string | null;
        ended_at: string | null;
        message_count: number;
      }
    | undefined;
  if (!s) return { built: false, reason: "no session" };

  const msgs = db
    .prepare(
      "SELECT id, role, content, tool_name, timestamp FROM messages WHERE session_id = ? ORDER BY timestamp ASC, id ASC",
    )
    .all(sessionId) as MsgRow[];
  if (!msgs.length) return { built: false, reason: "no messages" };

  const newSig = signature(msgs);
  const prev = db
    .prepare("SELECT source_sig, kind FROM session_digest WHERE session_id = ?")
    .get(sessionId) as { source_sig: string; kind: string } | undefined;
  // Don't clobber an agent-authored digest with the extractive one, and skip
  // when nothing changed.
  if (prev && prev.source_sig === newSig && prev.kind === "extractive") return { built: false, reason: "unchanged" };
  if (prev && prev.kind === "agent") return { built: false, reason: "agent-authored" };

  const isNatural = (m: MsgRow): boolean =>
    (m.role === "user" || m.role === "assistant") && !m.tool_name && !!m.content && !NON_NL.test(m.content);

  // tasks = genuine user turns (each request ≈ a task). Multiple, not one.
  const tasks: Anchored[] = [];
  for (const m of msgs) {
    if (tasks.length >= 8) break;
    if (m.role === "user" && isNatural(m)) {
      const t = clip(m.content!, 160);
      if (t) tasks.push({ text: t, id: m.id });
    }
  }

  // decisions = natural-language lines that read like a commitment (NOT tool
  // dumps — a rendered RULES/TODO blob contains "dùng"/"plan set" but isn't one).
  const decisions: Anchored[] = [];
  for (const m of msgs) {
    if (decisions.length >= 6) break;
    if (isNatural(m) && DECISION_RE.test(m.content!)) decisions.push({ text: clip(m.content!, 160), id: m.id });
  }

  // errors = TOOL-RESULT output that looks like a failure (not tool CALLS, whose
  // command text may contain "error" like `-ErrorAction`).
  const errors: Anchored[] = [];
  for (const m of msgs) {
    if (errors.length >= 5) break;
    if (m.content && TOOL_RESULT.test(m.content) && ERROR_RE.test(m.content))
      errors.push({ text: clip(m.content, 160), id: m.id });
  }

  // paths_touched = session root/cwd + path-like tokens seen in messages.
  const pathSet = new Set<string>();
  if (s.project_root) pathSet.add(s.project_root);
  if (s.cwd && s.cwd !== s.project_root) pathSet.add(s.cwd);
  for (const m of msgs) {
    if (pathSet.size >= 12 || !m.content) continue;
    const found = m.content.match(PATH_RE);
    if (found) for (const p of found.slice(0, 3)) if (p.length >= 6 && p.length <= 120) pathSet.add(p);
  }
  const paths = [...pathSet].slice(0, 12);

  // outcome = last couple of natural-language lines.
  const outcome = msgs
    .filter(isNatural)
    .slice(-2)
    .map((m) => clip(m.content!, 200))
    .join(" ⋯ ");

  const meta: DigestMeta = {
    source: s.source,
    host: s.host ?? "unknown",
    project_root: s.project_root,
    messages: s.message_count,
    from: s.started_at,
    to: s.ended_at,
  };

  const digestText = [
    ...tasks.map((t) => t.text),
    ...decisions.map((d) => d.text),
    ...errors.map((e) => e.text),
    outcome,
    paths.join(" "),
    meta.source,
    meta.host,
    meta.project_root ?? "",
  ]
    .filter(Boolean)
    .join("\n");

  db.prepare(
    `INSERT INTO session_digest
       (session_id, kind, tasks, paths, decisions, errors, outcome, meta, source_sig, digest_text, updated_at)
     VALUES (@sid, 'extractive', @tasks, @paths, @decisions, @errors, @outcome, @meta, @sig, @text, @now)
     ON CONFLICT(session_id) DO UPDATE SET
       kind='extractive', tasks=@tasks, paths=@paths, decisions=@decisions, errors=@errors,
       outcome=@outcome, meta=@meta, source_sig=@sig, digest_text=@text, updated_at=@now`,
  ).run({
    sid: sessionId,
    tasks: JSON.stringify(tasks),
    paths: JSON.stringify(paths),
    decisions: JSON.stringify(decisions),
    errors: JSON.stringify(errors),
    outcome,
    meta: JSON.stringify(meta),
    sig: newSig,
    text: digestText,
    now: new Date().toISOString(),
  });
  return { built: true };
}

/** Backfill/refresh digests for every non-empty session (hash-guarded). */
export function digestBackfill(dbPath: string = BRAIN_DB): { built: number; scanned: number } {
  const db = openBrain(dbPath);
  try {
    const ids = db.prepare("SELECT id FROM sessions WHERE message_count > 0").all() as { id: string }[];
    let built = 0;
    for (const { id } of ids) {
      try {
        if (buildDigest(db, id).built) built++;
      } catch {
        /* fail-open: one bad session never blocks the rest */
      }
    }
    return { built, scanned: ids.length };
  } finally {
    db.close();
  }
}

function parse<T>(json: string | null, fallback: T): T {
  if (!json) return fallback;
  try {
    return JSON.parse(json) as T;
  } catch {
    return fallback;
  }
}

/** Read one session's digest (parsed), or null. */
export function getDigest(dbPath: string = BRAIN_DB, sessionId: string): Digest | null {
  const db = openBrain(dbPath);
  try {
    const r = db.prepare("SELECT * FROM session_digest WHERE session_id = ?").get(sessionId) as
      | Record<string, string | null>
      | undefined;
    if (!r) return null;
    return {
      session_id: r.session_id as string,
      kind: (r.kind as string) ?? "extractive",
      tasks: parse<Anchored[]>(r.tasks, []),
      paths: parse<string[]>(r.paths, []),
      decisions: parse<Anchored[]>(r.decisions, []),
      errors: parse<Anchored[]>(r.errors, []),
      outcome: (r.outcome as string) ?? "",
      meta: parse<DigestMeta>(r.meta, {
        source: "",
        host: "unknown",
        project_root: null,
        messages: 0,
        from: null,
        to: null,
      }),
      updated_at: r.updated_at ?? null,
    };
  } finally {
    db.close();
  }
}

export interface DigestHit {
  session_id: string;
  snippet: string;
  meta: DigestMeta;
}

/** Recall "digest lane": FTS over session digests (word → trigram fallback). */
export function searchDigests(
  query: string,
  opts: { limit?: number; project?: string; dbPath?: string; recency?: boolean } = {},
): DigestHit[] {
  const q = query.trim();
  if (!q) return [];
  const limit = opts.limit ?? 10;
  const db = openBrain(opts.dbPath ?? BRAIN_DB);
  try {
    const run = (table: string, match: string): DigestHit[] => {
      try {
        const rows = db
          .prepare(
            `SELECT d.session_id, d.meta, snippet(${table}, 0, '[', ']', '…', 16) AS snippet
             FROM ${table} f JOIN session_digest d ON d.id = f.rowid
             WHERE ${table} MATCH @m
             ORDER BY bm25(${table}) LIMIT @lim`,
          )
          .all({ m: match, lim: limit }) as { session_id: string; meta: string | null; snippet: string }[];
        return rows.map((r) => ({
          session_id: r.session_id,
          snippet: r.snippet,
          meta: parse<DigestMeta>(r.meta, {
            source: "",
            host: "unknown",
            project_root: null,
            messages: 0,
            from: null,
            to: null,
          }),
        }));
      } catch {
        return [];
      }
    };
    const terms = q
      .toLowerCase()
      .split(/\s+/)
      .map((t) => t.replace(/["()*:^]/g, ""))
      .filter(Boolean);
    if (!terms.length) return [];
    const filtered = opts.project
      ? (hits: DigestHit[]) => hits.filter((h) => h.meta.project_root === opts.project)
      : (hits: DigestHit[]) => hits;
    const word = filtered(run("session_digest_fts", terms.map((t) => `"${t}"`).join(" ")));
    const hits = word.length ? word : filtered(run("session_digest_fts_tri", `"${terms.join(" ")}"`));
    // Freshest relevant session first (agents stop pulling stale digests).
    return blendRecency(hits, (h) => h.meta.to, recencyEnabled(opts.recency));
  } finally {
    db.close();
  }
}
