// READ BEFORE WRITE — layer-1 latch (user 2026-10-08, from Dept_FA: "nếu agent ko đọc các full docs phải nhảy cảnh báo, ép
// đọc hết, ko dc sót nữa"). Measured at Dept_FA 2026-10-07: one agent failed three times although the rule and a reminder
// hook existed — it skimmed (offset/limit · grep · sed -n) and acted. A reminder is not enough; this BLOCKS.
//
// The SOURCE of "what was read" is the session TRANSCRIPT the hook already receives (`transcript_path`): every Read result is
// recorded there with `startLine · numLines · totalLines` (and `truncatedByTokenCap`), so coverage is exact even when the tool
// cut a long file. No second ledger to keep in sync (HP điều 3 — one source). grep / sed / Get-Content never count as reading.
//
// Generated into `<hooks>/read-first.cjs` by `zemory hook guard`; guard.cjs calls it. Plain stdlib, written with String.raw so
// backslashes are literal — DO NOT use backticks or dollar-brace inside the source below.
export const READ_FIRST_SOURCE = String.raw`// Read-before-write latch - generated by zemory hook guard. The rules live in policy.json (read_first).
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const norm = (p) => String(p || "").replace(/\\/g, "/").replace(/\/+$/, "").toLowerCase();

// Shell commands that only LOOK: they run before the docs are read (searching memory, listing, git status...).
const LOOK = new Set(["ls", "dir", "pwd", "cd", "echo", "cat", "type", "head", "tail", "wc", "grep", "rg", "findstr", "tree",
  "stat", "file", "du", "df", "which", "where", "whoami", "hostname", "date", "true", "sleep",
  "get-childitem", "gci", "get-content", "gc", "select-string", "sls", "get-item", "gi", "test-path", "get-process", "gps",
  "get-date", "measure-object", "select-object", "where-object", "foreach-object", "format-table", "format-list", "out-string",
  "sort-object", "group-object", "convertfrom-json", "convertto-json", "resolve-path", "split-path", "join-path",
  "get-ciminstance", "write-output", "write-host", "get-filehash", "get-acl", "get-command", "get-location", "set-location",
  "start-sleep", "out-null", "get-member", "invoke-webrequest", "irm", "iwr", "curl"]);
const GIT_LOOK = /^(status|log|diff|show|rev-parse|ls-files|fetch|branch|remote|rev-list|blame|grep|ls-remote|describe|shortlog|cat-file|check-ignore)$/;
const ZEMORY_LOOK = [/^memory (search|show|digest|info|stats|scan|status|channel status)\b/, /^(peers|gates|validate|doctor|help|--version|-v)\b/,
  /^paths check\b/, /^sync --check\b/, /^plan (search|ls|show)\b/, /^changelog search\b/];

function segments(cmd) {
  const out = [];
  let cur = "", q = null;
  for (let i = 0; i < cmd.length; i++) {
    const c = cmd[i];
    if (q) { cur += c; if (c === q && cmd[i - 1] !== "\\") q = null; continue; }
    if (c === '"' || c === "'") { q = c; cur += c; continue; }
    if (c === ";" || c === "\n" || c === "&" || c === "|") { out.push(cur); cur = ""; continue; }
    cur += c;
  }
  out.push(cur);
  return out.map((s) => s.trim()).filter(Boolean);
}
function words(seg) {
  let s = seg.replace(/^\$[A-Za-z_][\w:]*\s*=\s*/, "").replace(/^\(+/, ""); // PowerShell "$x = <cmd>" · "(cmd)"
  const toks = s.split(/\s+/).map((t) => t.replace(/^["'(]+|["')]+$/g, "")).filter(Boolean);
  while (toks.length && (/^[A-Za-z_]\w*=/.test(toks[0]) || /^(sudo|env|command|nohup|time|nice|exec|&)$/i.test(toks[0]))) toks.shift();
  return toks;
}
// Does a shell command ACT (write · run a script · commit · send)? Anything not on the LOOK list acts — strict by design:
// before the docs are read, only reading is allowed.
function shellActs(cmd) {
  // A redirect into a real file writes (2>&1 · >$null · >/dev/null · > nul do not).
  if (/(^|[^\d&])>{1,2}\s*(?!&|\$null|\/dev\/null|nul\b)[^\s|;&]/i.test(cmd.replace(/(["'])(?:(?!\1).)*\1/g, ""))) return true;
  for (const seg of segments(cmd)) {
    // A property ASSIGNMENT on an object writes, whatever command produced it: "(Get-Item f).LastWriteTime = ..." (real trial).
    if (/\)\s*\.\s*[A-Za-z_]\w*\s*=(?!=)/.test(seg)) return true;
    // A request that SENDS data acts (a mail API, a webhook): curl -X POST / -d · Invoke-WebRequest -Method Post / -Body.
    if (/^(curl|invoke-webrequest|iwr|irm|invoke-restmethod)\b/i.test(seg.trim()) && /\s(-X\s*(POST|PUT|PATCH|DELETE)|-d\b|--data|-F\b|-Method\s+(Post|Put|Patch|Delete)|-Body\b|-InFile\b)/i.test(seg)) return true;
    const w = words(seg);
    if (!w.length) continue;
    const name = w[0].replace(/\\/g, "/").split("/").pop().toLowerCase().replace(/\.exe$/, "");
    if (LOOK.has(name)) continue;
    if (name === "git" && GIT_LOOK.test(w[1] || "")) continue;
    if (name === "zemory" && ZEMORY_LOOK.some((re) => re.test(w.slice(1).join(" ")))) continue;
    if (name === "node" && w[1] && /dist[\\/]cli\.js$/.test(w[1]) && ZEMORY_LOOK.some((re) => re.test(w.slice(2).join(" ")))) continue;
    return true;
  }
  return false;
}

// The files the action needs, beyond the always-required set: a case's spec, and the trigger table of AGENTS.md (only the
// triggers a machine can recognise for certain).
function extraFor(rf, root, targets, cmd) {
  const out = [];
  const caseRoot = norm(rf.case_root || "tasks");
  const cases = new Set();
  for (const t of targets) {
    const m = new RegExp("^" + caseRoot.replace(/[.*+?^()|[\]\\{}]/g, "\\$&") + "/([^/]+)/").exec(norm(t));
    if (m) cases.add(m[1]);
  }
  if (cmd) {
    const re = new RegExp("(?:^|[\\s\"'/\\\\])" + (rf.case_root || "tasks") + "[\\\\/]([A-Za-z0-9_.-]+)[\\\\/]", "gi");
    let m;
    while ((m = re.exec(cmd))) cases.add(m[1].toLowerCase());
  }
  for (const c of cases) {
    let dir = null;
    try {
      const real = fs.readdirSync(path.join(root, rf.case_root || "tasks")).find((d) => d.toLowerCase() === c);
      if (real) dir = path.join(rf.case_root || "tasks", real);
    } catch {}
    if (!dir) continue;
    for (const f of rf.case_files || ["spec.md"]) if (fs.existsSync(path.join(root, dir, f))) out.push(path.join(dir, f).replace(/\\/g, "/"));
  }
  for (const tr of rf.triggers || []) {
    if (!tr.read || !fs.existsSync(path.join(root, tr.read))) continue;
    let hit = false;
    if (tr.when === "new_dir") {
      hit = targets.some((t) => !fs.existsSync(path.dirname(path.join(root, t))));
      if (!hit && cmd) hit = /(^|[\s;&|(])(mkdir|md|new-item\b[^;&|]*-itemtype\s+["']?directory)/i.test(cmd);
    } else if (tr.when === "path_prefix") {
      hit = targets.some((t) => norm(t).startsWith(norm(tr.prefix) + "/"));
    } else if (tr.when === "cmd_re" && cmd) {
      try { hit = new RegExp(tr.re, "i").test(cmd); } catch {}
    }
    if (hit) out.push(tr.read);
  }
  return out;
}

function expand(root, list) {
  const out = [];
  for (const rel of list) {
    if (rel.endsWith("/*.md")) {
      const dir = rel.slice(0, -5);
      try {
        for (const f of fs.readdirSync(path.join(root, dir)).sort()) if (/\.md$/i.test(f)) out.push(dir + "/" + f);
      } catch {}
    } else if (fs.existsSync(path.join(root, rel))) out.push(rel);
  }
  return [...new Set(out)];
}

// What the transcript says was read (after the last context compaction) and what this session itself wrote.
function ledger(transcript) {
  const reads = new Map(), own = new Map(), events = new Map();
  const ev = (k, e) => { if (!events.has(k)) events.set(k, []); events.get(k).push(e); };
  let text;
  try { text = fs.readFileSync(transcript, "utf8"); } catch { return null; }
  for (const line of text.split("\n")) {
    if (line.includes("compact_boundary") || line.includes("\"isCompactSummary\":true")) {
      let j; try { j = JSON.parse(line); } catch { continue; }
      if (j.subtype === "compact_boundary" || j.isCompactSummary === true) { reads.clear(); events.clear(); } // compacted: what was read is gone
      continue;
    }
    if (!line.includes("\"toolUseResult\"")) continue;
    let j; try { j = JSON.parse(line); } catch { continue; }
    const r = j.toolUseResult, ts = Date.parse(j.timestamp || "") || 0;
    if (!r || typeof r !== "object") continue;
    if (r.type === "text" && r.file && r.file.filePath) {
      const k = norm(r.file.filePath);
      const rd = { kind: "read", s: Number(r.file.startLine) || 1, n: Number(r.file.numLines) || 0, t: Number(r.file.totalLines) || 0, ts };
      if (!reads.has(k)) reads.set(k, []);
      reads.get(k).push(rd);
      ev(k, rd);
    } else if (r.filePath && (r.type === "update" || r.type === "create" || r.structuredPatch)) {
      own.set(norm(r.filePath), Math.max(own.get(norm(r.filePath)) || 0, ts));
      ev(norm(r.filePath), { kind: "own", ts });
    }
  }
  return { reads, own, events };
}

// Coverage of ONE file by the reads that are still valid (none older than a change made by someone else).
function coverage(abs, L) {
  const k = norm(abs);
  let mtime = 0, lines = 0;
  try { const st = fs.statSync(abs); mtime = st.mtimeMs; lines = fs.readFileSync(abs, "utf8").split("\n").length; } catch { return null; }
  // Walk the file's events in order. Two reads with a DIFFERENT line count and no write of ours between them = someone else
  // changed the file in between (our own later edit would otherwise hide that change behind our mtime) ⇒ earlier reads void.
  let live = [], lastT = null, ownSince = false, reset = false;
  for (const e of L.events.get(k) || []) {
    if (e.kind === "own") { ownSince = true; continue; }
    if (lastT !== null && e.t !== lastT && !ownSince) { live = []; reset = true; }
    live.push(e);
    lastT = e.t;
    ownSince = false;
  }
  const lastOwn = L.own.get(k) || 0;
  const changedByOther = !(lastOwn && mtime <= lastOwn + 3000);
  const valid = live.filter((r) => !changedByOther || r.ts >= mtime - 1000);
  const stale = (reset || changedByOther) && (L.reads.get(k) || []).length > 0 && valid.length < (L.reads.get(k) || []).length;
  if (!valid.length) return { full: false, got: 0, total: lines, stale };
  // One VERSION read end to end is enough: group the reads by the line count they saw (our own edits change the count, and
  // the lines we wrote ourselves need no reading).
  let best = { got: 0, total: lines };
  const byT = new Map();
  for (const r of valid) { if (!byT.has(r.t)) byT.set(r.t, []); byT.get(r.t).push(r); }
  for (const [t, rs] of byT) {
    const total = t || lines;
    const marks = new Uint8Array(total + 2);
    for (const r of rs) for (let i = r.s; i < r.s + r.n && i <= total; i++) marks[i] = 1;
    let got = 0;
    for (let i = 1; i <= total; i++) got += marks[i];
    if (got >= total) return { full: true, got, total, stale: false };
    if (got / total > best.got / (best.total || 1)) best = { got, total };
  }
  return { full: false, got: best.got, total: best.total, stale };
}

// null = let through · string = the blocking message.
function readFirst(payload, root, policy) {
  const rf = policy && policy.read_first;
  if (!rf || !Array.isArray(rf.required)) return null;
  const transcript = payload.transcript_path;
  if (!transcript || !fs.existsSync(transcript)) return null; // a host without a transcript: no evidence, no verdict
  const tool = payload.tool_name || "";
  const ti = payload.tool_input || {};
  const targets = [];
  let cmd = "";
  if (tool === "Write" || tool === "Edit" || tool === "MultiEdit" || tool === "NotebookEdit") {
    const p = ti.file_path || ti.notebook_path || "";
    const rel = path.relative(root, path.resolve(root, p)).replace(/\\/g, "/");
    if (!p || rel.startsWith("..") || path.isAbsolute(rel)) return null; // outside the repo: not this latch's business
    targets.push(rel);
  } else if (typeof ti.command === "string" && ti.command) {
    cmd = ti.command;
    if (!shellActs(cmd)) return null;
  } else {
    return null; // Read · Glob · Grep · everything that only looks
  }
  const need = expand(root, rf.required.concat(extraFor(rf, root, targets, cmd)));
  const L = ledger(transcript);
  if (!L) return null;
  const missing = [];
  for (const rel of need) {
    const c = coverage(path.join(root, rel), L);
    if (!c || c.full) continue;
    missing.push("  - " + rel + (c.stale ? "  (read BEFORE someone else changed it - read it again)" : "  (read " + c.got + "/" + c.total + " lines)"));
  }
  if (!missing.length) return null;
  return "BLOCKED (guard layer 1): NOT READ IN FULL - this repo requires reading these files completely in this session before acting:\n" +
    missing.join("\n") +
    "\nRead each with the Read tool to the last line (a long file: keep reading with offset until the end). grep / sed / head / Get-Content do not count." +
    " After a context compaction the files must be read again. There is no flag for this.";
}

module.exports = { readFirst, shellActs, coverage, ledger };
`;
